Safety
AlphaDev87/timba-api pull request #18
Opened 2024-03-07 13:49 UTC by alvarezrrj

# Description

- Volvimos  a usar `bcrypt.hash()` para hashear contraseñas porque es mas segura.
- Arreglada la respuesta de crear jugador
- Actualizado el README con endpoints de agente
- Enlazamos user-agent string a los tokens de acceso para identificar cuando un token se usa desde un dispositivo distinto al que se usó para obtenerlo
- Invalidamos tokens previos del usuario en cada login (solo los que tengan la misma user-agent string, para permitirle que tenga sesiones abiertas en mas de un dispositivo)
- Agregué un endpoint `/auth/logout` para invalidar tokens

2024-03-07 22:23 UTC, AlphaDev87 requested changes

2024-03-07 22:23 UTC, AlphaDev87 commented on src/routes/agent.router.ts
> +  // console.log(req);
Eliminar console.logs y comentarios

2024-03-07 22:23 UTC, AlphaDev87 commented on src/routes/auth.router.ts
> +authRouter.post("/logout", validateToken(), AuthController.logout);
El logout para que sirve?

2024-03-07 22:23 UTC, AlphaDev87 commented on src/types/response/jwt.ts
> +  jti: string; // JWT ID
no commnets

2024-03-08 10:55 UTC, alvarezrrj commented on src/routes/auth.router.ts
> +authRouter.post("/logout", validateToken(), AuthController.logout);
Es para inhabilitar un token. Lo agregué porque [OAuth](https://oauth.net/2/token-revocation/) dice que tiene que estar presente. 

Le hice un cambio y es que el usuario tiene que estar logueado para inhabilitar un token, y el token le tiene que pertenecer

2024-03-12 17:52 UTC, AlphaDev87 approved these changes

2024-03-12 17:53 UTC, merged